{
 "title": "BOSH Director",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(boshdirector_vitals_cpu_sys, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(boshdirector_vitals_cpu_sys{environment=~\"$environment\"}, bosh_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "boshdirector_vitals_cpu_user{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director CPU User %"
    },
    {
     "expr": "boshdirector_vitals_cpu_sys{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director CPU Sys %"
    },
    {
     "expr": "boshdirector_vitals_cpu_wait{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director CPU Wait %"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "boshdirector_vitals_mem_percentage{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director RAM Percentage"
    },
    {
     "expr": "boshdirector_vitals_swap_percentage{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director Swap Percentage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "boshdirector_vitals_disk_persistent_percentage{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director Persistent Disk Usage"
    },
    {
     "expr": "boshdirector_vitals_disk_ephemeral_percentage{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director Ephemeral Disk Usage"
    },
    {
     "expr": "boshdirector_vitals_disk_system_percentage{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}",
     "legendFormat": "$bosh_director System Disk Usage"
    }
   ]
  }
 ]
}